### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by tonioloewald** [exif-js/exif-js#107]
The way exif gets data is unnecessarily bad for performance. Suppose I want one tag (in my case, orientation), getImageData actually parses EXIF, IPTC, and XMP data before I can ask for my one tag). A simple improvement would be:

getData() accepts a third "types" parameter, which defaults to {exif: true, iptc: true, xmp: true} and then handleBinaryFile only gets the data the user asks for:

```
    // FIX add types parameter
    function getImageData(img, callback, types) {
        if (typeof types !== 'object') {
          types = {
            exif: true,
            iptc: true,
            xmp: true,
          };
        }
        function handleBinaryFile(binFile) {
          // FIX use types parameter to skip stuff
            var data = types.exif ? findEXIFinJPEG(binFile) : false;
            var iptcdata = types.iptc ? findIPTCinJPEG(binFile) : false;
            var xmpdata= types.xmp ? findXMPinJPEG(binFile) : false;
            img.exifdata = data || {};
            img.iptcdata = iptcdata || {};
            img.xmpdata = xmpdata || {};
            if (callback) {
                callback.call(img);
            }
        }
```

I should add that the code in handleBinaryFile is unnecessarily verbose; you could write three lines of code instead of six:

`img.iptcdata = types.iptc ? findIPTCinJPEG(binFile);`

And just have the parsers return `{}` instead of `false`.

This simple change gives me a >2x speedup when handling an image, and given that parsing a smartphone photograph takes 800-2000ms on a fast laptop this is not insignificant.

**Comment by tonioloewald** [comment]
Actually the performance hit is less significant than I thought because the big hit is the http request that pulls the file a second time (sigh).

**Comment by OMaiZaregoto** [comment]
Thanks.
Ur advice does really help on my project about APP.
The performance hit is much more enlarged in a small APP than a laotop.
I use it to solve the orientation issue in Hybrid APP which using HTML input(type="file") to select photo from users' mobilephone.

Thanks Indeed.
