### ISSUE TITLE
Make XMP optional + move example page

### ISSUE THREAD

**Issue by bartvanderwal** [exif-js/exif-js#114]
In issue #106 @artfree mentioned that the new XMP functionality can slow things up.
So it's better to make it optional, and turn it off by default.

You now have to call EXIF.enableXmp()` before XMP is retrieved. Sadly I couldn't find an example image with XMP info, so I couldn't really test it. But I checked that indeed the call wasn't made.

In the course of this issue I also moved the example page to the root, and added the missing `xml2json` function as suggested in other issues (#84 and #92).

**Comment by bartvanderwal** [comment]
This is really a breaking change, so semver says major version number should be updated. By since XMP doesn't seem to be used that much, and I'm just a minor contributor, I chose minor instead.

**Comment by zlzdp** [comment]
@bartvanderwal in this project, /example/Bush-dog.jpg has xmp info, I testd it in http://metapicz.com/#landing, I can see the xmp info, but exif.js can not read xmp info.
xmp is not working well.
