### ISSUE TITLE
IOS can't get time

### ISSUE THREAD

**Issue by SupaFan** [exif-js/exif-js#129]
rt

**Comment by yogeshsaroya** [comment]
have you found any solution for iOS ?

**Comment by miracle857** [comment]
@yogeshsaroya @SupaFan  have you found any solution for iOS ?

**Comment by yogeshsaroya** [comment]
> @yogeshsaroya @SupaFan have you found any solution for iOS ?

due to security iOS or other high end android phone not allowed to share this info. That's why iOS device is secure.
