### ISSUE TITLE
trying to run in iOS with PhoneGap/Steroids and only getting 5 Exif Tags

### ISSUE THREAD

**Issue by mixersoft** [exif-js/exif-js#13]
Works fine in FF/Win8, but on the iPad I only get these 5 Exif tags:

Orientation
ExifIFDPointer
ColorSpace
PixelXDimension
PixelYDimension

Is there anything you are doing in binaryajax.js that is not strictly HTML5?

**Comment by expntly** [comment]
@markevans @jseidelin This doesn't seem to be entirely true.

http://stackoverflow.com/questions/39311406/ios-exif-geolocation-data-missing

Any idea what's going on?
