### ISSUE TITLE
Exif-js not working

### ISSUE THREAD

**Issue by mbrynard** [exif-js/exif-js#157]
I am using Chrome browser to read GPS data from an image using exif-js
I first got an error message:
cross origin requests are only supported for protocol schemes http data chrome chrome-extension
Then tried to rectify this by adding: Access-Control-Allow-Origin: http://localhost
within the <script> area. (not sure if this is in the right place)
This gives an error: Uncaught SyntaxError: Unexpected token 

My code below:
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>EXIF example with inline EXIF info</title>
</head>
 <img src="test.jpg" id="img1" height="500"/>
    <pre><div>Longitude and latitude: <span id="LonLat"> </span></div></pre>
    <br/>
    
<script type="text/javascript" src="exif-js//exif.js"></script>
 <script type="text/javascript">
 "use strict";

Access-Control-Allow-Origin: http://localhost
        window.onload=getExif;

        function getExif() {
            var img1 = document.getElementById("img1");
            
            EXIF.getData(img1, function() {
  var latitude = EXIF.getTag(this, "GPSLatitude");
  var longitude = EXIF.getTag(this, "GPSLongitude");
  var LonLat = document.getElementById("LonLat");
  LonLat.innerHTML = GPSLongitude;
});
EXIF.getData(img1, function() {
   alert(EXIF.pretty(this));
});
}
</script>
  </body>
</html>

**Comment by mbrynard** [comment]
The script did not display correctly in my previous posting:
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>EXIF example with inline EXIF info</title>
</head>

 <img src="test.jpg" id="img1" height="500"/>

    <pre><div>Longitude and latitude: <span id="LonLat"> </span></div></pre>
    <br/>
    
<script type="text/javascript" src="exif-js//exif.js"></script>
 <script type="text/javascript">
 "use strict";

Access-Control-Allow-Origin: http://localhost

        window.onload=getExif;
alert("Hello");

        function getExif() {
            var img1 = document.getElementById("img1");
            
            EXIF.getData(img1, function() {
  var latitude = EXIF.getTag(this, "GPSLatitude");
  var longitude = EXIF.getTag(this, "GPSLongitude");
  var LonLat = document.getElementById("LonLat");
  LonLat.innerHTML = GPSLongitude;

});
EXIF.getData(img1, function() {
   alert(EXIF.pretty(this));
});
}

</script>


 
   
</body>
</html>

**Comment by mbrynard** [comment]
My script did not display well in the previous posting:

<img src="test.jpg" id="img1" height="500"/>
 <div>Longitude and latitude: <span id="LonLat"> </span></div>
<script type="text/javascript" src="exif-js//exif.js"></script>
 <script type="text/javascript">
 "use strict";

Access-Control-Allow-Origin: http://localhost

        window.onload=getExif;
        function getExif() {
            var img1 = document.getElementById("img1");
            
            EXIF.getData(img1, function() {
  var latitude = EXIF.getTag(this, "GPSLatitude");
  var longitude = EXIF.getTag(this, "GPSLongitude");
  var LonLat = document.getElementById("LonLat");
  LonLat.innerHTML = GPSLongitude;
});
EXIF.getData(img1, function() {
   alert(EXIF.pretty(this));
});
}
</script>

**Comment by mbrynard** [comment]
Bart
Thanks for the suggestions.
I did preview the script before posting, but somehow it gets changed by the editor.
I also loaded your previously posted examples (Bush-dog etc) on my localhost and they also do not work.
I get the same cross-origin error messages in the Chrome-JavaScript debugger.

**Comment by mbrynard** [comment]
I have finally managed to solve my problem of reading the exif data from an image and solving the problem of cross browser access..
I found a script for handling cross browser requests in IIS (http://gkb.wikidot.com/setting-cors-on-iis-8) to be placed in the web.config file in the web directory where my Javascript resides.
The script comprises 9 lines : 
<system.webServer>
  <httpProtocol>
    <customHeaders>
      <add name="Access-Control-Allow-Origin" value="*" />
      <add name="Access-Control-Allow-Headers" value="Content-Type" />
      <add name="Access-Control-Allow-Methods" value="GET, POST, PUT, DELETE, OPTIONS" />
    </customHeaders>
  </httpProtocol>
</system.webServer>

After running my program as http://localhost/index.html it works perfectly.

**Comment by bartvanderwal** [comment]
Hello,
Good that you found a solution.
You cannot just paste XML in an issue. Or so it seems.

Your solution is very platform/stack specific, so it's not relevant to a part of exif-users. I have added some specifics to the issue name. Please provide context for other users, so they can see if your issue is relevant for them. Enabling CORS is done differently on the different application-servers/backends like Apache, IIS, nodjes nginx, etc.
