### ISSUE TITLE
获取不到图片任何信息！求助

### ISSUE THREAD

**Issue by Lkkpower** [exif-js/exif-js#237]

**Comment by Lkkpower** [comment]
> ![image](https://user-images.githubusercontent.com/24646979/77290876-165c1e80-6d18-11ea-98b7-129fd46be3aa.png)
> ![image](https://user-images.githubusercontent.com/24646979/77290919-2e33a280-6d18-11ea-8039-7acaca8366d5.png)
> 
> vue 技术栈

**Comment by caoshuhao** [comment]
hello, execuse me ,i have the same question,i want to know how did you solve it.
