### ISSUE TITLE
Not working properly with ReactJs

### ISSUE THREAD

**Issue by Developer-Nijat** [exif-js/exif-js#239]
![not_valid_marker_exifjs](https://user-images.githubusercontent.com/51002164/80032475-49065c00-84fc-11ea-8af0-1e7d4f2912e8.png)

What is problem here ? not working with react js 

```
import EXIF from "exif-js";

getImageDetails = () => {
        var file = document.getElementById("initial_stage");
        EXIF.getData(file, function() {
            var exifData = EXIF.getAllTags(this);
            if (exifData) {
                console.log('exifData: ', JSON.stringify(exifData));
            } else {
                console.log("No EXIF data found in image '" + file + "'.");
            }
        });
    };

<img
  onClick={this.getImageDetails}
  id="initial_stage"
  src={`/storage/${this.state.details.initial_stage}`}
/>;

```
"laravel": 5.8
"react": "^16.2.0",
"exif-js": "^2.3.0",

**Comment by Developer-Nijat** [comment]
Problem solved. It is laravel voyager admin image uploading issue

Solution: Store image with file input . Now metadata is not corrupted it is ok. But when store images with image input then metadata corrupted. Maybe helpful to others

**Comment by fragmnt** [comment]
> 
> 
> Problem solved. It is laravel voyager admin image uploading issue
> 
> Solution: Store image with file input . Now metadata is not corrupted it is ok. But when store images with image input then metadata corrupted. Maybe helpful to others

Can you post an example of your fixed code?

**Comment by Developer-Nijat** [comment]
> > Problem solved. It is laravel voyager admin image uploading issue
> > Solution: Store image with file input . Now metadata is not corrupted it is ok. But when store images with image input then metadata corrupted. Maybe helpful to others
> 
> Can you post an example of your fixed code?

İ already posted code. Problem with admin panel. I used laravel voyager admin panel. for example i have projects and project photo. Before project photo input type was image picker (from voyager admin bread) after i changed input type to file now photo stored original format
