### ISSUE TITLE
file-demo 拍照，xs max照片旋转

### ISSUE THREAD

**Issue by biezhenyu** [exif-js/exif-js#242]
xs max照片旋转（前置镜头），后端拿到照片也是旋转
![WechatIMG50](https://user-images.githubusercontent.com/23213442/80691642-1f07f780-8b03-11ea-87b3-dfb67ff29a26.jpeg)

**Comment by biezhenyu** [comment]
就是使用了你的放大之后，照片还是旋转

**Comment by chenxiaoyao6228** [comment]
> 就是使用了你的放大之后，照片还是旋转

老铁解决了吗
