### ISSUE TITLE
Cant we just read the first 64k? 

### ISSUE THREAD

**Issue by mmichelli** [exif-js/exif-js#48]
https://github.com/robertdmunn/exif-js/blob/master/src/exif.js#L394

**Comment by diegocr** [comment]
Hi, I was wondering what's the point behind your request, to enhance performance?

If so, i think it should be pretty fast already, for example i use exif.js to deal with RAW photos, and to process ~40MB of data it takes a few milliseconds.

I.e:

```
19:36:39.896 exif: timer started index.js:109
19:36:39.897 Got file of length 37835264 exif.js:386:20
19:36:39.900 exif: 3.92ms index.js:118
19:36:39.900 EXIF Object { Compression: 6, ImageDescription: "SONY DSC", Make: "SONY ", Model: "DSLR-A900", Orientation: 1, XResolution: 350, YResolution: 350, ResolutionUnit: 2, Software: "DSLR-A900 v1.00", DateTime: "2008:12:22 16:37:58", 30 more… } 1 index.js:121:4
```
(Firefox 41 on a core i7 laptop)

Hence, i'm against such change unless it's provided through an opt-in option :-)

**Comment by mmichelli** [comment]
You are totally correct, I thought the size of the files was slowing down my project, and this was the only solution. After more investigation, exif-js is not slow at all. Thanks for the good response.
