### ISSUE TITLE
It would be nice to have some documentation, README.md, docs

### ISSUE THREAD

**Issue by bartvanderwal** [exif-js/exif-js#55]
It could be my limited intelligence.

But I actually think there would be a lot of people who would prefer to have a little documentation, like some samples in the `README.md` to get them going more quickly using this library.

Now you have to get it all from the code itself, which just takes more time.

**Comment by bartvanderwal** [comment]
Ah wait, I already started to do something but I had missed the included [example](https://github.com/exif-js/exif-js/blob/master/example/index.html) completely

**Comment by ZaneCEO** [comment]
Some formal documentation would be very useful indeed

**Comment by bartvanderwal** [comment]
I actually already wrote some. I'll do a pull request when I changed my code examples in that with those in the index.html which I discovered after my weiting. As I won't have to test/improve those like I'd still need todo with mine. Weekend first...

**Comment by bartvanderwal** [comment]
I did a pull request a while ago...

**Comment by axelson** [comment]
For linkage the PR is #57 

I really wish more open source projects focused on documentation
