### ISSUE TITLE
Remove exif data?

### ISSUE THREAD

**Issue by tinganho** [exif-js/exif-js#9]
Hi @jseidelin , I wonder if you know how to strip off EXIF data from file using JS?

I'm building a client-side cropping solution. It reads file content from the FileReader API. And I base64 encode the file content to insert it as a src in an img tag. Than I'm using canvas to crop the image and it is here everything goes wrong. I can't crop with canvas, because canvas don't know what EXIF data is.

I've searched the whole Internet didn't find anything on how-to do it using Javascript

**Comment by nickdesaulniers** [comment]
Draw the image to a canvas and present that for download: https://github.com/codepo8/image-data-cleaner/blob/c732dc05ff4cc8946301e0b9cd30c8c5a33815c6/scripts/cleaner.js#L56-L59
