### ISSUE TITLE
I want to display those information in tabular form

### ISSUE THREAD

**Issue by rsunil92** [exif-js/exif-js#98]

**Comment by bartvanderwal** [comment]
this code? those information?
Please be more specific.

**Comment by rsunil92** [comment]
The Information i get after execution should come in tabular form. because now its showing message. i want it in same or other webpage. 

i tried to do it, but i am not getting a way. 

help me.

**Comment by isherwood** [comment]
You need to learn to parse an object and output the data as you like. that's outside the scope of this plugin. Here's an example of something I'm doing to put the data into a table:

```
    // exposure
    var apertureRaw = EXIF.getTag(this, 'FNumber');
    cbExif.aperture = 'f/' + apertureRaw.numerator / apertureRaw.denominator; 

    $('#cb-popup-box .cb-popup-exif').append('<div><b>Exposure:</b> ' + cbExif.shutter + ' sec @ ' + cbExif.aperture + '</div>');

    
```
